title: Lia C. Bozarth
description: 2nd Year PhD student at University of Michigan, School of Information (UMSI).
show_downloads: true
google_analytics:
theme: jekyll-theme-leap-day
github.owner_name: Lia Bozarth

